source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '9.0'

target 'DCFrame_Example' do
  pod 'DCFrame', :path => '../'
end

target 'DCFrame_ExampleTests' do
  pod 'DCFrame', :path => '../'
end
