source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '9.0'

target 'DCFrame_Example' do
  pod 'DCFrame', :path => '../'
end

target 'DCFrame_ExampleTests' do
  pod 'DCFrame', :path => '../'
end

post_install do |installer|
  devTargets = ['DCFrame']
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if devTargets.include? target.name
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "NO"
        config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "NO"
      else
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
        config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
      end
    end
  end
end
